// Code generated by "stringer -type Kind -linecomment"; DO NOT EDIT.

package block

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Blank-0]
	_ = x[Error-1]
	_ = x[Separator-2]
	_ = x[Comment-3]
	_ = x[Directive-4]
	_ = x[RequestLine-5]
	_ = x[URLContinuation-6]
	_ = x[Header-7]
	_ = x[HeaderBodySeparator-8]
	_ = x[BodyOpen-9]
	_ = x[BodyClose-10]
	_ = x[BodyContent-11]
	_ = x[FileBody-12]
	_ = x[PreRequestScriptOpen-13]
	_ = x[ResponseScriptOpen-14]
	_ = x[ScriptContent-15]
	_ = x[ScriptClose-16]
	_ = x[ResponseRedirect-17]
	_ = x[ResponseReference-18]
}

const _Kind_name = "BlankErrorSeparatorCommentDirectiveRequestLineURLContinuationHeaderHeaderBodySeparatorBodyOpenBodyCloseBodyContentFileBodyPreRequestScriptOpenResponseScriptOpenScriptContentScriptCloseResponseRedirectResponseReference"

var _Kind_index = [...]uint8{0, 5, 10, 19, 26, 35, 46, 61, 67, 86, 94, 103, 114, 122, 142, 160, 173, 184, 200, 217}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
