// Code generated by "stringer -type Kind -linecomment"; DO NOT EDIT.

package block

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Blank-0]
	_ = x[Error-1]
	_ = x[Separator-2]
	_ = x[Comment-3]
	_ = x[Directive-4]
	_ = x[LocalVariable-5]
	_ = x[RequestLine-6]
	_ = x[URLContinuation-7]
	_ = x[Header-8]
	_ = x[HeaderBodySeparator-9]
	_ = x[BodyOpen-10]
	_ = x[BodyClose-11]
	_ = x[BodyContent-12]
	_ = x[FileBody-13]
	_ = x[PreRequestScriptOpen-14]
	_ = x[ResponseScriptOpen-15]
	_ = x[ScriptContent-16]
	_ = x[ScriptClose-17]
	_ = x[ResponseRedirect-18]
	_ = x[ResponseReference-19]
}

const _Kind_name = "BlankErrorSeparatorCommentDirectiveLocalVariableRequestLineURLContinuationHeaderHeaderBodySeparatorBodyOpenBodyCloseBodyContentFileBodyPreRequestScriptOpenResponseScriptOpenScriptContentScriptCloseResponseRedirectResponseReference"

var _Kind_index = [...]uint8{0, 5, 10, 19, 26, 35, 48, 59, 74, 80, 99, 107, 116, 127, 135, 155, 173, 186, 197, 213, 230}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
