// Code generated by "stringer -type state -linecomment"; DO NOT EDIT.

package block

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[stateInitial-0]
	_ = x[stateRequestPrelude-1]
	_ = x[stateScript-2]
	_ = x[stateRequestHeaders-3]
	_ = x[stateRequestBody-4]
	_ = x[stateRequestPostBody-5]
}

const _state_name = "InitialRequestPreludeScriptRequestHeadersRequestBodyRequestPostBody"

var _state_index = [...]uint8{0, 7, 21, 27, 41, 52, 67}

func (i state) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_state_index)-1 {
		return "state(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _state_name[_state_index[idx]:_state_index[idx+1]]
}
