// Code generated by "stringer -type Severity -linecomment"; DO NOT EDIT.

package syntax

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SeverityInvalid-0]
	_ = x[SeverityWarning-1]
	_ = x[SeverityError-2]
}

const _Severity_name = "invalidwarningerror"

var _Severity_index = [...]uint8{0, 7, 14, 19}

func (i Severity) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Severity_index)-1 {
		return "Severity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Severity_name[_Severity_index[idx]:_Severity_index[idx+1]]
}
