// Code generated by "stringer -type Kind -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Error-0]
	_ = x[Separator-1]
	_ = x[Text-2]
	_ = x[Ident-3]
	_ = x[Dollar-4]
	_ = x[At-5]
	_ = x[Dot-6]
	_ = x[LParen-7]
	_ = x[RParen-8]
	_ = x[LAngle-9]
	_ = x[RAngle-10]
	_ = x[Comma-11]
	_ = x[Colon-12]
	_ = x[Eq-13]
	_ = x[Number-14]
	_ = x[OpenInterp-15]
	_ = x[CloseInterp-16]
	_ = x[OpenScript-17]
	_ = x[CloseScript-18]
	_ = x[ResponseRedirect-19]
	_ = x[ResponseRedirectForce-20]
	_ = x[Comment-21]
}

const _Kind_name = "ErrorSeparatorTextIdentDollarAtDotLParenRParenLAngleRAngleCommaColonEqNumberOpenInterpCloseInterpOpenScriptCloseScriptResponseRedirectResponseRedirectForceComment"

var _Kind_index = [...]uint8{0, 5, 14, 18, 23, 29, 31, 34, 40, 46, 52, 58, 63, 68, 70, 76, 86, 97, 107, 118, 134, 155, 162}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
