// Code generated by "stringer -type Kind -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[Error-1]
	_ = x[Separator-2]
	_ = x[Text-3]
	_ = x[Ident-4]
	_ = x[Dollar-5]
	_ = x[At-6]
	_ = x[Dot-7]
	_ = x[LParen-8]
	_ = x[RParen-9]
	_ = x[Comma-10]
	_ = x[Colon-11]
	_ = x[Eq-12]
	_ = x[StringLiteral-13]
	_ = x[Number-14]
	_ = x[OpenInterp-15]
	_ = x[CloseInterp-16]
	_ = x[OpenScript-17]
	_ = x[CloseScript-18]
}

const _Kind_name = "EOFErrorSeparatorTextIdentDollarAtDotLParenRParenCommaColonEqStringLiteralNumberOpenInterpCloseInterpOpenScriptCloseScript"

var _Kind_index = [...]uint8{0, 3, 8, 17, 21, 26, 32, 34, 37, 43, 49, 54, 59, 61, 74, 80, 90, 101, 111, 122}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
