// Code generated by "stringer -type Kind -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Error-0]
	_ = x[Comment-1]
	_ = x[Separator-2]
	_ = x[Text-3]
	_ = x[Quote-4]
	_ = x[Ident-5]
	_ = x[Dollar-6]
	_ = x[At-7]
	_ = x[Dot-8]
	_ = x[LParen-9]
	_ = x[RParen-10]
	_ = x[LAngle-11]
	_ = x[RAngle-12]
	_ = x[Comma-13]
	_ = x[Colon-14]
	_ = x[Eq-15]
	_ = x[Number-16]
	_ = x[OpenInterp-17]
	_ = x[CloseInterp-18]
	_ = x[OpenScript-19]
	_ = x[CloseScript-20]
	_ = x[ResponseRedirect-21]
	_ = x[ResponseRedirectForce-22]
	_ = x[ResponseReference-23]
}

const _Kind_name = "ErrorCommentSeparatorTextQuoteIdentDollarAtDotLParenRParenLAngleRAngleCommaColonEqNumberOpenInterpCloseInterpOpenScriptCloseScriptResponseRedirectResponseRedirectForceResponseReference"

var _Kind_index = [...]uint8{0, 5, 12, 21, 25, 30, 35, 41, 43, 46, 52, 58, 64, 70, 75, 80, 82, 88, 98, 109, 119, 130, 146, 167, 184}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
